INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO genre (genre_name) VALUES
('Action'),
('Adventure'),
('Role-playing game'),
('Fantasy'),
('Simulation'),
('Strategy'),
('First-person shooter'),
('Sports'),
('Puzzle'),
('Horror'),
('Fighting'),
('Survival'),
('Massively multiplayer');


INSERT INTO developers (developer_name) VALUES
('Blizzard Entertainment'),
('Bungie Inc.'),
('High Moon Studios'),
('Radical Entertainment'),
('Rockstar Games'),
('Rockstar North'),
('Obsidian Entertainment'),
('Gunfire Games'),
('Nintendo'),
('CD Projekt RED'),
('Epic Games'),
('People Can Fly'),
('Mojang Studios'),
('Xbox Game Studios'),
('4J Studios'),
('Double Eleven'),
('Infinity Ward'),
('Bethesda Game Studios'),
('InnerSloth LLC'),
('PlayEveryWhere'),
('Square Enix'),
('Psyonix');


INSERT INTO publishers (publisher_name) VALUES
('Blizzard Entertainment'),
('Activision'),
('Bungie Inc.'),
('Rockstar Games'),
('Bethesda Softworks'),
('Gearbox Publishing'),
('Nintendo'),
('CD Projekt RED'),
('Warner Bros. Games'),
('Epic Games'),
('Mojang Studios'),
('Xbox Game Studios'),
('Telltale Games'),
('Sony Interactive Entertainment'),
('InnerSloth LLC'),
('Square Enix'),
('Psyonix');

INSERT INTO lists (list_name, user_id) VALUES
('Currently Playing', 1),
('Want To Play', 1),
('Finished Games', 1),
('Favorite Games', 1),
('Game Library', 1),
('Currently Playing', 2),
('Want To Play', 2),
('Finished Games', 2),
('Favorite Games', 2),
('Game Library', 2);

INSERT INTO video_games (game_name, game_logo, description, release_date) VALUES
('Destiny', 'https://i.ibb.co/VpfCYPT/destiny-logo-1n7t45dciywzuwck-fotor-202308081266.png', 'Sci-fi shooter, explore the universe, join Guardians in epic battles, loot, and co-op play.', '2014-09-09'),
('Destiny 2', 'https://image.api.playstation.com/vulcan/img/rnd/202011/0400/3PetyfDv6TpzxVQtBKYnWq8o.png?w=440&thumb=false', 'The sequel to the original hit including expanded worlds, new subclasses, raids, and ongoing multiplayer challenges.', '2017-09-06'),
('Grand Theft Auto V', 'https://image.api.playstation.com/vulcan/ap/rnd/202202/2811/x9SuHZAiRn0uJXB1IKteIgcw.png?w=440&thumb=false', 'Immerse yourself in a sprawling open-world crime saga set in Los Santos. With three distinct protagonists, engage in daring heists, explore a vibrant city, and partake in various activities from driving to flying, creating a dynamic and engaging experience.', '2013-09-17'),
('World of Warcraft', 'https://pbs.twimg.com/profile_images/1027920204494503937/BeoTuplx_400x400.jpg', 'Enter the immersive universe of Azeroth in this MMORPG. Embark on quests, engage in raids, select from diverse classes, and experience both player-versus-environment and player-versus-player gameplay in a richly detailed fantasy world.', '2004-11-23'),
('Fallout: New Vegas', 'https://assets-prd.ignimgs.com/2021/12/08/falloutnv-1638924156844.jpg', 'Step into the post-apocalyptic Mojave Desert, where your choices shape the outcome of this RPG. Encounter factions vying for control, navigate moral dilemmas, and uncover a compelling narrative in a world ravaged by nuclear catastrophe.', '2010-10-19'),
('Remnant II', 'https://image.api.playstation.com/vulcan/ap/rnd/202306/0220/0b3c160e4f974e40e614cb2d409a1f24c90304343e205727.png?w=440&thumb=false', 'Remnant II pits survivors of humanity against new deadly creatures and god-like bosses across terrifying worlds. Play solo or co-op with two other friends to explore the depths of the unknown to stop an evil from destroying reality itself.', '7-25-2023'),
('The Legend of Zelda: Breath of the Wild', 'https://i.ibb.co/M58QxwY/most-annoying-monsters-breath-of-the-wild-fotor-20230808121211.png', 'Embark on a breathtaking open-world adventure as you explore Hyrule, solve intricate puzzles, and master the untamed wilderness, all while uncovering the secrets of a land steeped in legend.', '2017-03-03'),
('The Witcher 3: Wild Hunt', 'https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmHlktOHar3lVl6rY.png?w=440&thumb=false', ' Immerse yourself in an epic RPG journey as Geralt of Rivia, a monster hunter navigating an immersive world. Your choices influence the narratives course, creating a rich and impactful gameplay experience.', '2015-05-19'),
('Red Dead Redemption 2', 'https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png?w=440&thumb=false', 'Experience the Wild West through the eyes of Arthur Morgan, an outlaw grappling with morality. With stunning landscapes and meaningful decisions, the game weaves a compelling tale of loyalty and survival.', '2018-10-26'),
('Fortnite', 'https://i.pinimg.com/originals/c2/0d/21/c20d2168ee2dbaecae37c903ab1b99a2.jpg', 'Engage in the global phenomenon of Battle Royale, where you build, fight, and squad up to outlast opponents in evolving multiplayer matches, all while enjoying regular updates and social gaming experiences.', '2017-07-25'),
('Minecraft', 'https://image.api.playstation.com/vulcan/img/cfn/11307uYG0CXzRuA9aryByTHYrQLFz-HVQ3VVl7aAysxK15HMpqjkAIcC_R5vdfZt52hAXQNHoYhSuoSq_46_MT_tDBcLu49I.png?w=440&thumb=false', 'Unleash your creativity in a limitless block-based world, crafting, building, and surviving as you explore varied landscapes, mine resources, and design structures limited only by your imagination.', '2011-11-18'),
('Call of Duty: Modern Warfare', 'https://image.api.playstation.com/cdn/UP0002/CUSA08829_00/xmKUnAOenEAKspB3FlOg80aQZfEoCYcE.png?w=440&thumb=false', 'Immerse yourself in intense FPS action through a gripping campaign and thrilling multiplayer warfare, experiencing modern military conflicts with cinematic storytelling and competitive gameplay.', '2019-10-25'),
('The Elder Scrolls V: Skyrim', 'https://image.api.playstation.com/vulcan/ap/rnd/202110/1921/DOyNIDQAQvQyAUPG90iY9A4U.png?w=440&thumb=false', 'Embark on a vast fantasy realm as the Dragonborn, navigating quests, mastering magic, and engaging in epic battles, all while shaping the fate of the land with your choices.', '2011-11-11'),
('Super Mario Odyssey', 'https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg', 'Join Marios globe-trotting adventure across imaginative worlds, engaging in platforming challenges, and experiencing a whimsical journey filled with discovery and nostalgia.', '2017-10-27'),
('Overwatch', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Overwatch_circle_logo.svg/2048px-Overwatch_circle_logo.svg.png', 'Dive into team-based shooter action, choosing from diverse heroes with unique abilities, engaging in strategic gameplay, and competing against players worldwide in dynamic multiplayer matches.', '2016-05-24'),
('Among Us', 'https://image.api.playstation.com/vulcan/img/rnd/202107/0115/D5IIJwm65MLMPENwWzzO7rjd.png?w=440&thumb=false', 'Uncover the impostor in a social deduction game set aboard a spaceship, as trust and deceit intertwine in a race against time to identify the traitor among your crewmates.', '2018-06-15'),
('Animal Crossing: New Horizons', 'https://animalcrossing.nintendo.com/new-horizons/assets/img/global/logos/logo-acnh-en.png', 'Relax in a charming life simulation, building your dream island paradise, interacting with delightful animal villagers, and personalizing your virtual getaway.', '2020-03-20'),
('Cyberpunk 2077', 'https://image.api.playstation.com/vulcan/ap/rnd/202111/3013/cKZ4tKNFj9C00giTzYtH8PF1.png?w=440&thumb=false', 'Immerse yourself in a futuristic RPG set in an immersive city, where you enhance your body with cybernetics, navigate complex narratives, and shape the destiny of a technologically advanced society.', '2020-12-10'),
('Final Fantasy VII Remake', 'https://image.api.playstation.com/vulcan/img/cfn/11307-dNapclgq_VqNtQ98Xp_LxovvAdjd5AknZhd_-k2Cckq9FPtKDXAHk-ODCfvDKChH6hkEO0VLtj7Vk4E-Z8G707oe0N.png?w=440&thumb=false', 'Rediscover the classic RPG with a modern twist, following Cloud and his allies as they rebel against the oppressive Shinra corporation, merging nostalgia with innovative storytelling.', '2020-04-10'),
('Super Smash Bros. Ultimate', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Super_Smash_Bros._Ultimate_logo.svg/2560px-Super_Smash_Bros._Ultimate_logo.svg.png', 'Engage in iconic crossover fighting, pitting Nintendo characters against each other in thrilling multiplayer battles that celebrate gaming history.', '2018-12-07'),
('Rocket League', 'https://image.api.playstation.com/vulcan/ap/rnd/202305/2619/2271c8b1eda07957588a7b2078967ae12e72db12d9a5a60d.png?w=440&thumb=false', 'Experience high-speed, physics-based soccer with cars, engaging in exhilarating multiplayer action that combines sports and vehicular mayhem.', '2015-07-07');

INSERT INTO reviews (game_id, user_id, rating, review_title, review_body) VALUES
(1, 1, 5, 'Test Review Title!', 'Test Review Body!'),
(2, 1, 3, 'Test Review Title 2!', 'Test Review Body 2!'),
(3, 1, 4, 'Test Review Title 3!', 'Test Review Body 3!'),
(4, 1, 2, 'Test Review Title 4!', 'Test Review Body 4!'),
(5, 1, 1, 'Test Review Title 5!', 'Test Review Body 5!');

INSERT INTO average_rating (review_id, user_id, thumb_up_down) VALUES
(1, 1, true),
(2, 2, false);

INSERT INTO game_genre (game_id, genre_id) VALUES
(1, 7),
(1, 13),
(1, 1),
(1, 2),
(2, 7),
(2, 13),
(2, 1),
(2, 2),
(3, 1),
(3, 3),
(3, 5),
(4, 2),
(4, 4),
(4, 13),
(4, 3),
(5, 2),
(5, 3),
(5, 7),
(5, 12),
(6, 1),
(6, 3),
(6, 4),
(7, 1),
(7, 2),
(7, 3),
(7, 4),
(8, 1),
(8, 2),
(8, 3),
(8, 4),
(9, 1),
(9, 2),
(9, 3),
(10, 1),
(10, 7),
(10, 12),
(10, 13),
(11, 2),
(11, 4),
(11, 12),
(12, 1),
(12, 7),
(12, 13),
(13, 1),
(13, 2),
(13, 3),
(13, 4),
(14, 1),
(14, 2),
(14, 9),
(15, 1),
(15, 7),
(15, 13),
(16, 3),
(16, 6),
(16, 10),
(17, 2),
(17, 5),
(18, 1),
(18, 2),
(18, 5),
(18, 7),
(19, 1),
(19, 2),
(19, 3),
(19, 4),
(20, 6),
(20, 12),
(21, 8),
(21, 6);


INSERT INTO game_developers (game_id, developer_id) VALUES
(1, 2),
(1, 3),
(1, 4),
(2, 2),
(3, 5),
(3, 6),
(4, 1),
(5, 7),
(6, 8),
(7, 9),
(8, 10),
(9, 5),
(10, 11),
(10, 12),
(11, 13),
(11, 14),
(11, 15),
(11, 16),
(12, 17),
(13, 18),
(14, 9),
(15, 1),
(16, 19),
(16, 20),
(17, 9),
(18, 10),
(19, 21),
(20, 9),
(21, 22);


INSERT INTO game_publishers (game_id, publisher_id) VALUES
(1, 2),
(1, 3),
(2, 3),
(3, 4),
(4, 1),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 4),
(10, 10),
(10, 9),
(11, 11),
(11, 12),
(11, 13),
(11, 14),
(12, 2),
(13, 5),
(14, 8),
(15, 1),
(16, 15),
(17, 7),
(18, 8),
(19, 16),
(20, 7),
(21, 17);









